# Generated by Django 6.0.6 on 2026-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Idohou Augustin', max_length=120)),
                ('headline', models.CharField(default='Backend Developer · DevOps · AI Engineer', help_text='Sous-titre affiché sous le nom', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Photo de profil', upload_to='about/')),
                ('location', models.CharField(default='Cotonou, Bénin', max_length=120)),
                ('available', models.BooleanField(default=True, help_text='Disponible pour de nouveaux projets')),
                ('resume', models.FileField(blank=True, help_text='CV téléchargeable (PDF)', upload_to='about/')),
                ('intro', models.TextField(help_text="Court paragraphe d'introduction (le pitch).")),
                ('mission', models.TextField(help_text='Ma mission — pourquoi je fais ce métier.')),
                ('approach', models.TextField(blank=True, help_text='Mon approche / ma méthode de travail.')),
            ],
            options={
                'verbose_name': 'À propos',
                'verbose_name_plural': 'À propos',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text="Slug d'icône (rendu via template, ex: shield, rocket, code, server)", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Slug Simple Icons (ex: django, docker, postgresql). Vide = icône générique.', max_length=60),
        ),
    ]
